### ISSUE TITLE
Wrong axis labels on reliability diagrams for non-mean functionals

### ISSUE THREAD

**Issue by ogrisel** [lorentzenchr/model-diagnostics#124]
The `xlabel` and `ylabel` values are currently hardcoded:

- https://github.com/lorentzenchr/model-diagnostics/blob/78ace74e267052029e4ef37526dd2c0b20b20800/src/model_diagnostics/calibration/plots.py#L208-L214

In particular they are wrong whenever `functional != "mean"`.

**Comment by ogrisel** [comment]
I saw that when reading the following plot of the quantile regression example:

![image](https://github.com/lorentzenchr/model-diagnostics/assets/89061/8ef5a0cd-87ef-46bb-92d4-ef955f83aab8)

https://lorentzenchr.github.io/model-diagnostics/examples/quantile_regression/

**Comment by m-maggi** [comment]
@lorentzenchr I can take this up, I would use the variables `functional` and `level` when applicable to define the labels.

https://github.com/lorentzenchr/model-diagnostics/blob/78ace74e267052029e4ef37526dd2c0b20b20800/src/model_diagnostics/calibration/plots.py#L56-L67

- "mean": E(Y|X)
- "median": $q_{0.5}$(Y|X)
- "expectile": $e_{level}$(Y|X)
- "quantile": $q_{level}$(Y|X)

So for example for the expectile with level=0.8, the label on x axis would be
"prediction for  $e_{0.8}$(Y|X)"
and the label on the y axis:
"estimated $e_{0.8}$(Y|X)"
