### ISSUE TITLE
Add example for classification

### ISSUE THREAD

**Issue by lorentzenchr** [lorentzenchr/model-diagnostics#90]

**Comment by m-maggi** [comment]
@lorentzenchr I would be interested in preparing a notebook with the classification example.
I had in mind the [diabetes](https://www.openml.org/search?type=data&sort=runs&id=37&status=active) dataset from openml (binary classification) and as prediction I would use the probabilities rather than the 0/1 values. May I take this issue?

**Comment by lorentzenchr** [comment]
@m-maggi That would be great. My plan was to select a multiclass dataset, but start with binary classification and then at the end do muticlass in the same example.

**Comment by m-maggi** [comment]
@lorentzenchr I am not sure that scoring.LogLoss and scoring.decompose supports multiclass classification.
Even if I pass the labels (y_obs) as 0-1 numbers, e.g.
```
y_obs
array([[0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0]])
```
and the y_pred as probabilities, e.g.:
```
y_pred
array([[2.82768046e-04, 3.78847866e-03, 4.01418956e-07, 9.95928347e-01,
        4.45260932e-09],
       [1.78245930e-04, 6.92581643e-04, 2.75908954e-07, 9.99128896e-01,
        1.66188913e-10],
       [9.97679698e-01, 2.28082642e-03, 8.35177457e-06, 2.85211151e-05,
        2.60242731e-06],
       ...,
       [5.55868793e-04, 5.68932422e-03, 8.14883734e-07, 9.93753992e-01,
        4.64794321e-10],
       [2.04809925e-03, 1.71508586e-01, 6.89641344e-05, 8.26218013e-01,
        1.56337680e-04],
       [3.42651092e-03, 8.55108921e-01, 5.37811629e-04, 1.22499039e-01,
        1.84277167e-02]])
```
I think that already at this line something weird might happen:
https://github.com/lorentzenchr/model-diagnostics/blob/828e6540acbfe9094419e713794763358f16df51/src/model_diagnostics/scoring/scoring.py#L837

What do you think? In case the multiclass is not yet supported I would make an example with binary classification for this issue.

**Comment by lorentzenchr** [comment]
That’s true. It‘s not supported yet in logloss. But one can already look at calibration.

**Comment by m-maggi** [comment]
Ok, then I guess one could show the calibration plots for each class, see some examples below.
If that's alright with you I will use this approach and prepare a notebook which is similar to chapters 1-3 of the already existing regression example notebook.
![plot_bias](https://github.com/lorentzenchr/model-diagnostics/assets/124086916/4b0cbc30-5371-48ed-b94e-1501968b7848)
![bias](https://github.com/lorentzenchr/model-diagnostics/assets/124086916/a0c1aef1-b996-497e-8e44-aaf193e258fa)
![reliabilty_diagram](https://github.com/lorentzenchr/model-diagnostics/assets/124086916/cd16eef6-c9d4-47db-bdaf-a07197471d11)

**Comment by lorentzenchr** [comment]
Yes. For the reliability plots, if it‘s nit too many classes, one could put them in one single plot.

How would you design the API for multiclass logloss? So far with y_pred.shape = (n, m), m means different predictions/models.

**Comment by lorentzenchr** [comment]
After discussing the API with some colleagues, I think that I want to keep the rule "one column per model". For multiclass that means that we need the nested list/array type, e.g.
```python
import numpy as np
import polars as pl

n_classes = 3
# For the moment, I don't care that probabilities over classes ("rows") do not sum to 1.
m1 = pl.Series(
    name="model_1",
    values=np.arange(6).reshape((-1, n_classes)),
    dtype=pl.Array(width=3, inner=pl.Float64),
)
m2 = pl.Series(
    name="model_2",
    values=np.arange(6).reshape((-1, n_classes)) ** 2,
    dtype=pl.Array(width=3, inner=pl.Float64),
)
pl.DataFrame((m1, m2))
```
```
shape: (2, 2)
┌─────────────────┬───────────────────┐
│ model_1         ┆ model_2           │
│ ---             ┆ ---               │
│ array[f64, 3]   ┆ array[f64, 3]     │
╞═════════════════╪═══════════════════╡
│ [0.0, 1.0, 2.0] ┆ [0.0, 1.0, 4.0]   │
│ [3.0, 4.0, 5.0] ┆ [9.0, 16.0, 25.0] │
└─────────────────┴───────────────────┘
```

**Comment by m-maggi** [comment]
all right, then I guess it makes sense that I prepare the classification notebook already with this structure?

```python
_helper_pl = lambda data, name: pl.Series(
    name=name,
    values=data,
    dtype=pl.Array(width=data.shape[1], inner=pl.Float64)
    )
one = _helper_pl(m_trivial.predict_proba(X_test), "Trivial")
two = _helper_pl(m_logistic.predict_proba(X_test), "Logistic")
three = _helper_pl(m_hgbt.predict_proba(X_test), "HGBT")
df_pred_test = pl.DataFrame((one, two, three))
df_pred_test
```

```
shape: (3_240, 3)
┌──────────────────────────────────┬───────────────────────────────────┬──────────────────────────────────┐
│ Trivial                          ┆ Logistic                          ┆ HGBT                             │
│ ---                              ┆ ---                               ┆ ---                              │
│ array[f64, 4]                    ┆ array[f64, 4]                     ┆ array[f64, 4]                    │
╞══════════════════════════════════╪═══════════════════════════════════╪══════════════════════════════════╡
│ [0.332167, 0.330109, … 0.026754] ┆ [0.998101, 0.001808, … 0.000042]  ┆ [0.559818, 0.215987, … 0.019205] │
│ [0.332167, 0.330109, … 0.026754] ┆ [0.991165, 0.006663, … 0.002165]  ┆ [0.559818, 0.215987, … 0.019205] │
│ [0.332167, 0.330109, … 0.026754] ┆ [0.000874, 0.889818, … 0.108866]  ┆ [0.225447, 0.535581, … 0.026016] │
│ [0.332167, 0.330109, … 0.026754] ┆ [0.009242, 0.394858, … 0.000023]  ┆ [0.216521, 0.23785, … 0.019164]  │
│ …                                ┆ …                                 ┆ …                                │
│ [0.332167, 0.330109, … 0.026754] ┆ [0.001877, 0.990593, … 0.000452]  ┆ [0.217217, 0.558374, … 0.019225] │
│ [0.332167, 0.330109, … 0.026754] ┆ [0.003162, 0.166138, … 1.0146e-7… ┆ [0.22029, 0.227184, … 0.019497]  │
│ [0.332167, 0.330109, … 0.026754] ┆ [0.003527, 0.934552, … 0.04606]   ┆ [0.217205, 0.558196, … 0.019285] │
│ [0.332167, 0.330109, … 0.026754] ┆ [0.002822, 0.983751, … 0.000191]  ┆ [0.217272, 0.558236, … 0.019258] │
└──────────────────────────────────┴───────────────────────────────────┴──────────────────────────────────┘
```

I am new to polars, how would you transform the data to be usable by the `plot_reliability_diagram`? As example: we want to show the reliability diagram for the first class and have three columns in `y_pred` such that `plot_reliability_diagram` plots three lines (see example plot below, for practicality reasons I have not yet finished training the HistGradientBoostingClassifier)

![comparison](https://github.com/lorentzenchr/model-diagnostics/assets/124086916/a4991fe0-9801-43a8-99c6-694b720d7d47)

**Comment by lorentzenchr** [comment]
Again, let's start with **binary classification** but on a multiclass dataset (just select one class). Then the API is settled and we can later extent to multiclass once the API for that in implemented.

**Comment by lorentzenchr** [comment]
But yes, the way you plotted it, one reliability diagram with several models per class makes sense to me. This way, models are comparable.
