### ISSUE TITLE
scoring.decompose raises ValueError but input arrays meet the required conditions

### ISSUE THREAD

**Issue by m-maggi** [lorentzenchr/model-diagnostics#98]
## Description

There could be situations where calling scoring.decompose raises an Exception

```
Traceback (most recent call last):
  File "/workspaces/dev_env/minimal_example.py", line 9, in <module>
    decompose(
  File "/opt/conda/lib/python3.11/site-packages/model_diagnostics/scoring/scoring.py", line 848, in decompose
    score_recalibrated = scoring_function(y_obs, recalibrated, w)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/model_diagnostics/scoring/scoring.py", line 58, in __call__
    return np.average(self.score_per_obs(y_obs, y_pred), weights=weights)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/model_diagnostics/scoring/scoring.py", line 202, in score_per_obs
    raise ValueError(msg)
ValueError: Valid domain for degree=1 is y_obs >= 0 and y_pred > 0.
```

even though the input arrays y_obs and y_pred meet the required conditions.

## Code to reproduce
```python
import numpy as np
from model_diagnostics.scoring import decompose, PoissonDeviance

y = np.array([0., 0., 0., 0., 0., 0., 0.])
w = np.array([1000, 1000, 1000, 1000, 1000, 1000, 1000])
mx = np.array([5448.18388438, 50.01519906, 50.01704928, 50.01044007,
               50.01964483, 50.01714894, 5762.89508342])

decompose(
    y_obs=y,
    y_pred=mx,
    scoring_function=PoissonDeviance(),
    weights=w
)
```

## Expected result
To be discussed.

## Versions
OS linux-aarch64
model-diagnostics 1.0.0
Numpy 1.25.2
Python 3.11.5.final.0

**Comment by lorentzenchr** [comment]
@m-maggi Thanks for reporting. This is clearly an edge case. Which result would you expect as a user?
My guess is that the isotonic regression yields `0` as result which is then used as `y_pred`. Maybe raise a more informative warning/error?

**Comment by m-maggi** [comment]
@lorentzenchr thank you for the package. I agree. I would perhaps expect something like 
```
There was an error during the isotonic recalibration. 
The problem occurred at the following indices: idx
```
As `idx` I would show the indices at which the isotonic regression predicted values outside of the valid domain. One could then look at the design matrix at those indices.
Another option would just be a message like 
```
There was an error during the isotonic recalibration. 
With the provided y_pred it is not possible to compute the score decomposition.
```
Then the user would know in more detail where the error happened.

How could this be achieved with the current code structure? Currently it seems to me that the scoring_function (e.g. `HomogeneousExpectileScore`) does not know whether one is calling it at the actual score step

https://github.com/lorentzenchr/model-diagnostics/blob/1221224e499bf2a467134ce6921abef31df14e44/src/model_diagnostics/scoring/scoring.py#L847

or at the score step based on the recalibrated predictions

https://github.com/lorentzenchr/model-diagnostics/blob/1221224e499bf2a467134ce6921abef31df14e44/src/model_diagnostics/scoring/scoring.py#L848
